### ISSUE TITLE
Suggestion: Follow infobox colour theming

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [CalebWhiting/runelite-plugin-action-progress#1]
Could you make it so the box for the plugin follows the colour and transparency the info boxes use? Its nice to have everything matching.

example of clashing:
![image](https://user-images.githubusercontent.com/37377657/159612381-1c99c593-dfec-41e5-9279-b779c1265894.png)

Very cool plugin besides this!

**Comment by CalebWhiting** [comment]
Oh, I didn't realise those colours could be changed.

I'll look into it :)

**Comment by CalebWhiting** [comment]
Fixed :)
