### ISSUE TITLE
Inaccurate timer when using double ammo mould for smithing cannonballs

### ISSUE THREAD

**Issue by manray00** [CalebWhiting/runelite-plugin-action-progress#18]
The timer does not reflect the shorter duration of smithing cannonballs with a double ammo mould. The plugin also only shows 1 steel bar in your inventory as being used during each smelting action instead of 2. The timer will continue after there are no steel bars left in your inventory as well.
![doubleammomould1](https://user-images.githubusercontent.com/114882323/193475496-425d20b8-0ec3-471d-9330-44e991bf5c46.png)
![doubleammomould2](https://user-images.githubusercontent.com/114882323/193475502-9d491140-292c-4fb1-8c34-2202a824ec1e.png)

**Comment by jevonsp** [comment]
Not sure how actively maintained this plugin is, but I really love the visual bar and would really really like this issue to get fixed

just got the mould yday and its a very slight annoyance, but an annoyance never the less

**Comment by guillaume009** [comment]
I fixed this in #17. Not sure how to make it so the version of the plugin is updated in RuneLite to use that newest change though. I'm stuck using the version with the commit c13d6723. @CalebWhiting ?

**Comment by guillaume009** [comment]
Fixed this in my fork of the project. This should now be reflect in RuneLite

**Comment by guillaume009** [comment]
Please close this issue when you are available.
