### ISSUE TITLE
Not working for Jewlary enchantment

### ISSUE THREAD

**Issue by bennmapes** [CalebWhiting/runelite-plugin-action-progress#20]
Just tried this today for enchanting jewellery afk and doesn't seem to work. No progress bar shows up.

On Runelite 1.9.3.

**Comment by guillaume009** [comment]
Resolved in latest version. Please close this when you are available.

**Comment by guillaume009** [comment]
Found the issue. Will be fixed soon when I update the plugin on RuneLite.

**Comment by guillaume009** [comment]
Fix is now live. You can close this when you are available.

**Comment by bennmapes** [comment]
![image](https://github.com/CalebWhiting/runelite-plugin-action-progress/assets/1332575/823c5ef6-d319-4feb-b9df-505f32c67b41)

Can confirm it's now working, kinda hard to read since it's vertical but it works!
