### ISSUE TITLE
Not working for mith platebody's on prif anvil

### ISSUE THREAD

**Issue by Haris00911** [CalebWhiting/runelite-plugin-action-progress#22]
Started smithing on prif anvil and noticed the timer wasn't popping up. Tried restarting RuneLite and reinstalling plugin but still wouldn't show up. Tried using spacebar and clicking on the smithing item but neither worked. Attempted at 12pm CST 12/26/22

**Comment by guillaume009** [comment]
It isn't specific to prif anvil. It's a duplicated of #9. I'm looking into it, but it isn't trivial to do. Please close this issue when you are available, I'll use the one I linked to share progress.
