### ISSUE TITLE
Not working for creating antivenoms

### ISSUE THREAD

**Issue by Velite12** [CalebWhiting/runelite-plugin-action-progress#23]
5 zulrah scales per dose of antidote is what's used, but it'll only ever act on that specific dose count of potion, so 20 scales per 4 dose and with 27 4 dose that's just 27.

**Comment by guillaume009** [comment]
I don't have the herblore lvl to try antivenoms, but I found a similar issue for stamina pots. I fixed it for both. Let me know if you still have the issue, otherwise please close this.
