### ISSUE TITLE
[Feature request] Color blind options

### ISSUE THREAD

**Issue by DelVision** [CalebWhiting/runelite-plugin-action-progress#25]
Ability to customize the bar colors would be extremely useful especially when having the bar on second screen it would be nice to use something with more high contrast, also red/green color blindness is rather common issue so the bars are basically invisible for some people with the default colors.

**Comment by guillaume009** [comment]
I have made my own fork of this plugin in which I added settings to change the progress bar color. Just waiting on the plugin to be updated on RuneLite

https://github.com/runelite/plugin-hub/pull/4072

**Comment by mhollink** [comment]
@guillaume009 Would be great to also propose a pull request from the fork to this remote repo. That way the author can merge it whenever before ever making other changes. Elsewise your change might end up getting removed in later updates by not being present in this repository.

**Comment by guillaume009** [comment]
The plugin now points to my repo, so for now we should be ok. But it's a good suggestion. I'll try to periodically do PR toward this repo so that it's easy to merge if ever Caleb wants to take back the ownership

**Comment by guillaume009** [comment]
By the way, this has now been fixed in RuneLite. Feel free to close the issue when you are available
