### ISSUE TITLE
Plugin failed to build since 1.9.12

### ISSUE THREAD

**Issue by YvesW** [CalebWhiting/runelite-plugin-action-progress#27]
Plugin fails to build since the bump to 1.9.12 as can be seen in the action logs: https://github.com/runelite/plugin-hub/actions/runs/4374130743/jobs/7653171128

**Comment by guillaume009** [comment]
Created my fork of this plugin where I fixed this issue. It should now be usable.

**Comment by YvesW** [comment]
I noticed it in the RL discord indeed. Closing this issue now.
