### ISSUE TITLE
I have it installed but it's not appearing for any skills

### ISSUE THREAD

**Issue by necroburn** [CalebWhiting/runelite-plugin-action-progress#3]
Tested on cooking steaks at lumby range, no progress bar appeared.

Tried in resizable - Classic / Modern + Fixed

Turned off and on resources packs and UI skins but still nothing

**Comment by CalebWhiting** [comment]
At the moment the plugin is broken due to an issue that couldn't have been caught in testing, if the problem persists once the plugin is updated to 1.03.1 then please tell me.
Sorry for the inconvenience.

**Comment by necroburn** [comment]
when do you plan to update it?

**Comment by CalebWhiting** [comment]
> when do you plan to update it?

The update has been ready for almost 3 days, I'm just waiting for someone to approve it.

**Comment by CalebWhiting** [comment]
Thankfully the update has been approved, hopefully everything will work well for you now. If the problem persists, open another issue.
