### ISSUE TITLE
Pest Control Interruptions

### ISSUE THREAD

**Issue by aaronjau101** [CalebWhiting/runelite-plugin-action-progress#4]
Would be great if you could add some fixes for Pest Control interruptions. I like to fletch arrows while playing the minigame but get interrupted by poison, attacks, and shield dropped notifications. Great plugin otherwise!

**Comment by CalebWhiting** [comment]
I'll implement this soon, thanks for the suggestion.

**Comment by CalebWhiting** [comment]
> Would be great if you could add some fixes for Pest Control interruptions. I like to fletch arrows while playing the minigame but get interrupted by poison, attacks, and shield dropped notifications. Great plugin otherwise!
Does the shield dropping actually interrupt the action? That seems odd.
