### ISSUE TITLE
[Feature Request] Resize UI

### ISSUE THREAD

**Issue by BUCKFAE** [CalebWhiting/runelite-plugin-action-progress#8]
Awesome Plugin!
Would it be possible to add an option that allows to resize the overlay to match the other ones? Maybe just scale everything down to match the size?

![2022-07-02_22-40](https://user-images.githubusercontent.com/33499592/177015641-a500e15d-0d17-4d27-9531-7daaceaf1df5.png)

**Comment by guillaume009** [comment]
Resolved in latest version. Please close this when you are available.
